name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Execute a cada 12 horas
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Leila-Giangiardi
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages  # Ou a branch que você usa para GitHub Pages
