name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou o branch de onde você quer fazer o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: npm run build  # Ou o comando que você usa para construir o projeto

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

  
